### ISSUE TITLE
Send message is not working. I am able to do all other operations. 

### ISSUE THREAD

**Issue by moonrumble** [qlamp/jMSMQClient#1]

**Comment by moonrumble** [comment]
src/ionic/Msmq/Queue -> send method is not passing isTransactional flag.

**Comment by qlamp** [comment]
Hi moonrumble, 
The flag has been set to be true and is encapsulated into the method body, so you don't need to worry about it unless you would like to make it false, if you really want to do that, you need to fork it and contribute the change yourself.
Let me know if any question else.
